<wsdl20:descriptions xmlns:wsdl20="http://www.w3.org/ns/wsdl"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:translator="http://translator/web/ws/schema"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  targetNamespace="http://translator/web/ws/schema">
    <wsdl20:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   targetNamespace="http://translator/web/ws/schema" elementFormDefault="qualified">

            <xs:element name="getTranslationRequest">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="langFrom" type="xs:string"/>
                        <xs:element name="langTo" type="xs:string"/>
                        <xs:element name="text" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="getTranslationResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="resultCode" type="xs:string"/>
                        <xs:element name="errorMsg" type="xs:string"/>
                        <xs:element name="translation" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl20:types>
    <wsdl20:interface name="TranslatorPortType">
        <wsdl20:operation name="translate">
            <wsdl20:input element="translator:getTranslationRequest" />
            <wsdl20:output element="translator:getTranslationResponse" />
        </wsdl20:operation>
    </wsdl20:interface>
    <wsdl20:binding name="TranslatorSoap12Binding" type="translator:TranslatorPortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl20:operation name="translate">
            <soap12:operation soapAction="translate" style="document" />
            <wsdl20:input>
                <soap12:body use="literal" />
            </wsdl20:input>
            <wsdl20:output>
                <soap12:body use="literal" />
            </wsdl20:output>
        </wsdl20:operation>
    </wsdl20:binding>
</wsdl20:descriptions>
